# Generated by Django 2.0.3 on 2018-04-04 16:18

import ParkEasy.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', ParkEasy.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
