# Generated by Django 2.0.3 on 2018-04-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkEasy', '0002_auto_20180404_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_length',
            field=models.IntegerField(default=0),
        ),
    ]
